---

- name: Ensure we have curl
  apt:
      name: curl
      state: present

- name: Ensure we have docker-compose install file
  shell: "curl -L \"https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"

- name: Ensure the docker-compose has execute privileges
  file:
      path: /usr/local/bin/docker-compose
      mode: 0655

- name: Symlink to docker-compose to /usr/bin/docker-compose
  file:
      src: /usr/local/bin/docker-compose
      dest: "{{ docker_compose_symlink_path }}/docker-compose"
      state: link
  when: docker_compose_symlink